Default: &defaults
  database: choremaster.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: choremaster_test.sqlite3
  <<: *defaults

Staging:
  database: choremaster_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: choremaster_production.sqlite3
  poolsize: 100
  <<: *defaults
